@section('title','MM-cupid: ')
@section('meta_contents',"Myanmar Dating Website | Online Dating | Myanmar Cupid | MMCupid | သင့်ဖူးစာရှင်ကို ရှာဖွေလိုက်ပါ")
@section('meta_keywords','mmcupid | MMcupid | myanmar dating | find love | find lover | future boyfriend | future partner | future girlfriend | online dating | ဖူးစာဖက် | ရည်းစားရှာ | ရည်းစား | ဒိတ်')
@include('frontend.layouts.header')
@yield('content')
@yield('javascript')
@include('frontend.layouts.footer')